#!/usr/bin/env python

bld.SAMBA_BINARY('test_cli',
    includes='clients/registry/ common/ ../ common/protocol',  
    source='mdclient2.cpp ',
    ldflags='-L/home/ascohen/dev/samba_fresh/samba/trustwave/lib/ -lpe_pev -L/usr/lib/ -Wno-cast-qual -lstdc++fs -lssl -lcrypto -lzmq -lboost_system -lboost_log -lboost_thread',
    deps='tw-zmq')
    

bld.SAMBA_BINARY('shmem_cleaner',
    includes='clients/registry/ common/ ../ common/protocol',  
    source='shared_mem_tests_cleaner.cpp',
    ldflags='',
    deps='tw-credentials tw-session tw-sessions-cache')
    

    
bld.SAMBA_BINARY('shmem_user',
    includes='clients/registry/ common/ ../ common/protocol',  
    source='shared_mem_tests_user.cpp',
    ldflags='',
    deps='tw-credentials tw-session tw-sessions-cache')
    

bld.SAMBA_BINARY('shmem_inserter',
    includes='clients/registry/ common/ ../ common/protocol',  
    source='shared_mem_tests_inserter.cpp',
    ldflags='',
    deps='tw-credentials tw-session tw-sessions-cache')
    