#!/usr/bin/env ruby

folder = File.expand_path('.',__dir__)
$:.unshift(folder) unless $:.include?(folder)
folder = File.expand_path('./functional_tests',__dir__)
$:.unshift(folder) unless $:.include?(folder)
require 'mdcliapi2.rb'
require 'testRunner.rb'
require 'myLogger.rb'
require 'json'

xml_path = ARGV[0]
if  xml_path.nil? || xml_path.empty?
    xml_path="full.xml"
    puts "please specify the path of tests xml. currently using default: " + xml_path
end

runner = Test_Runner.new
runner.run_test_from_file(xml_path)
END {
    puts "closing log file"
   log.close
}
