#!/usr/bin/env python
   
bld.SAMBA_SUBSYSTEM('registry-actions',
	includes='.. ../../../common/ ../../../', 
    source='registry_action.cpp query_value.cpp enumerate_key.cpp key_exists.cpp value_exists.cpp',
    deps='tw-session tw-registry-client')