#!/usr/bin/env python
bld.SAMBA_SUBSYSTEM('tw-registry-client',  
    source='registry_client.cpp',
    deps='  registry_common registry samba-util ')

bld.SAMBA_BINARY('tw-registry-client-test',  
source='test.cpp',
deps='tw-registry-client tw-credentialslib tw-sessionslib util_reg smbclient smbclient-raw samba-util')
'''
bld.SAMBA_BINARY('tw-registry-client-test2',  
source='test2.cpp',
deps='tw-registry-client tw-common util_reg')
'''    