#!/usr/bin/env python

bld.RECURSE('clients')
bld.RECURSE('misc')  
bld.RECURSE('services')  

bld.SAMBA_BINARY('my_smb',
    includes='clients/registry/ misc/ misc/protocol',  
    source='smb_cli_test.cpp ',
    ldflags='-L/home/ascohen/dev/samba_fresh/samba/trustwave/lib/ -lpe_pev -L/usr/lib/ -lstdc++fs -lssl -lcrypto -lboost_system -lboost_log -lboost_thread',
    deps='tw-misc smb-actions registry-actions local-actions tw-logger')
    
