#!/usr/bin/env python

bld.SAMBA_BINARY('cdcm_worker',
    includes='clients/registry/ common/ common/protocol',  
    source='cdcm_worker_process.cpp message_worker.cpp ',
    ldflags='-L/home/ascohen/dev/samba_fresh/samba/trustwave/lib/ -lpe_pev -L/usr/lib/ -Wno-cast-qual -lstdc++fs -lssl -lcrypto -lzmq -lboost_filesystem -lboost_system -lboost_log -lboost_thread',
    deps='tw-sessionslib smb-actions registry-actions local-actions tw-logger tw-sessions-cache tw-zmq tw-singleton-runner')
    
